#!/bin/bash


[ "$1" != "" ] && CNT=$1 || CNT=3


set -e


run() {

E=$(find | grep "example-bin/run-examples")

for e in $E ; do

echo $e

$e

done
}



while true ; do

cnt=$((cnt + 1))

run

[ "$cnt" == "$CNT" ] && break

done
