#!/bin/bash


[ "$1" != "" ] && CNT=$1 || CNT=3
[ "$2" != "" ] && P=$2


set -e


run() {

E=$(find | grep "example-bin/run-examples")

for e in $E ; do

echo $e $P

$e $P

done
}



while true ; do

cnt=$((cnt + 1))

run

[ "$cnt" == "$CNT" ] && break

done
